### ISSUE TITLE
make uploaded files be world readable

### ISSUE THREAD

**Issue by ricardogsilva** [million12/docker-vsftpd#4]
It would be nice if the uploaded files were readable by other users.

My use case is that I want to be able to retrieve the files that are uploaded to this container by accessing its data volume. Currently the uploaded files are owned by the `ftp` user and group, which seem to have uid and gid of 14:80 respectively. The files also get permissions of `rw- --- ---` and this prevents any other user from reading them.

I really wouldn't want to mess with my retrieving user's groups so I'm thinking it would be nice if the uploaded files would be made world readable (`rw- r-- r--`).

This can be made by adding the `local_umask=022` setting to the `vsftpd.conf` file.

I've made this change in a local checkout of this repository and it seems to work OK. Would you be interested in adding this to your repo too? I can provide a Pull request if needed.

**Comment by pozgo** [comment]
Hi,

I'm only concern if generic settings should be set to world readable. I think those options should be specified either by adding another variable that we could pass do docker run or user could specify their own `vsftpd.conf` file by using `-v` flag 

This issue seems to be rather VSFTPD config specific rather than docker specific. 

I'm only saying that simply because I believe that not all users would want to have global access to files for all users.

**Comment by ricardogsilva** [comment]
That's a fair point. How about making it another env option, like the one that already exists for anonymous access?

**Comment by pozgo** [comment]
I think that's a better option.

If you don't mind, please send us PR and I'll merge it into the repo.  

Thanks!!!

**Comment by ricardogsilva** [comment]
Thanks for merging :)
